skip_commits:
  files:
    - '**/*.md'
    - '.vscode/**/*'
cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> .appveyor.yml'
matrix:
  fast_finish: true
build: 'off'
image: Visual Studio 2019
clone_folder: '%SCOOP%\buckets\Ash258'
environment:
  SCOOP: C:\SCOOP
  SCOOP_HOME: '%SCOOP%\apps\scoop\current'
  matrix:
    - PowerShell: 7
init:
  - pwsh: |
      (Get-PSProvider 'FileSystem').Home = 'C:\projects\'
      write-host "here22", $env:SCOOP, $env:SCOOP_HOME -f yellow
      if(!(Test-Path "$env:SCOOP_HOME")) {
        write-host "here" -f yellow
        git clone -q --depth=1 --branch 'NEW' 'https://github.com/Ash258/Scoop-Core' "$env:SCOOP_HOME"
        git clone -q --depth=1 'https://github.com/ScoopInstaller/Main' "$env:SCOOP\buckets\main"
      }
for:
  - matrix:
      only:
        - PowerShell: 6
    install:
      - pwsh: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - pwsh: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
on_finish:
  - pwsh: |
      $log = 'Install.log'
      if (Test-Path $log) {
        Get-Content $log -Raw | Write-Host
        Push-AppveyorArtifact $log
      }
